version: "3.0"

services:
  postgresql:
    image: postgres:9.6.8
    environment:
      POSTGRES_DB: bgdevs
      POSTGRES_USER: bgdevs
      POSTGRES_PASSWORD: bgdevs
    ports:
    - 5432:5432
    volumes:
    - ./postgres-data-bgdevs:/var/lib/postgresql/data

  service:
    image: yattbot/techmad:9
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
    - 8080:8080
    depends_on:
    - postgresql

  nginx:
    image: yattbot/jinx:11
    ports:
    - 80:80
    - 443:443
    restart: always
    depends_on:
    - service