version: "3.0"

services:
  postgresql:
    image: postgres:9.6.8
    environment:
      POSTGRES_DB: bgdevs
      POSTGRES_USER: bgdevs
      POSTGRES_PASSWORD: bgdevs
    ports:
    - 5432:5432

  #service:
  #  image: yattbot/techmad:6
  #  environment:
  #    SPRING_PROFILES_ACTIVE: postgres
  #  ports:
  #    - 80:8080
  #  depends_on:
  #    - postgresql